### PR TITLE
namespace

### PR DESCRIPTION
**Pull request by sam-kym**
Updated the namespace code block

### CODE REVIEW

**Comment by ThexXTURBOXx** [comment]
@ponnamkarthik This "fix" would be very appreciated! Could we get this merged? :)

**Comment by TheRedSpy15** [comment]
This definitely needs merged!

**Comment by ponnamkarthik** [comment]
Hey @dJani97 thanks for pointing it out i did it in hurry will push a new patch tomorrow reverting those changes

**Comment by nickesk** [comment]
Hi, the patch you speak of reverted the `minSdkVersion` change but not the `compileSdkVersion` change. The latter is still breaking our apps, so this should not be in a patch-level change.

**Pull request merged**
